/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import logica.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author edison
 */
public class Offices_window extends javax.swing.JFrame {

    /**
     * Creates new form offices_window
     */
    public Offices_window() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); 
        setResizable(false);
    }
    
    String rol_user;
     public void rol(String rol) {
        
        //De acuerdo al rol del usuario se habilitan los botones
        //correspondientes a la seguridad.

        rol_user = rol;
        if (rol_user.equals("admin") || rol_user.equals("Gerente") || rol_user.equals("Secretaria")) {

        }
        else{
            
            boton_registrar_sede.setEnabled(false);
            boton_modificar_sede.setEnabled(false);
            
        }     
        
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boton_registrar_sede = new javax.swing.JButton();
        boton_modificar_sede = new javax.swing.JButton();
        boton_mostrar_sedes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campo_buscar_sede = new javax.swing.JTextField();
        boton_buscar_sede = new javax.swing.JButton();
        boton_regresar_sedes = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SISTEMA FLASH");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), null));

        boton_registrar_sede.setBackground(new java.awt.Color(255, 255, 255));
        boton_registrar_sede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/nuevaSede.png"))); // NOI18N
        boton_registrar_sede.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_registrar_sede.setMaximumSize(new java.awt.Dimension(205, 129));
        boton_registrar_sede.setMinimumSize(new java.awt.Dimension(205, 129));
        boton_registrar_sede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_registrar_sedeActionPerformed(evt);
            }
        });

        boton_modificar_sede.setBackground(new java.awt.Color(255, 255, 255));
        boton_modificar_sede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/modificarSede.png"))); // NOI18N
        boton_modificar_sede.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_modificar_sede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_modificar_sedeActionPerformed(evt);
            }
        });

        boton_mostrar_sedes.setBackground(new java.awt.Color(255, 255, 255));
        boton_mostrar_sedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/mostrarSede.png"))); // NOI18N
        boton_mostrar_sedes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_mostrar_sedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_mostrar_sedesActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Sede");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Modificar Sede");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mostrar Sedes");

        campo_buscar_sede.setBackground(new java.awt.Color(236, 236, 237));

        boton_buscar_sede.setText("Buscar Sede");
        boton_buscar_sede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscar_sedeActionPerformed(evt);
            }
        });

        boton_regresar_sedes.setText("Regresar a la ventana anterior");
        boton_regresar_sedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_regresar_sedesActionPerformed(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 204, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/FlashLogo.png"))); // NOI18N
        jLabel19.setText("GESTION SEDES");
        jLabel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel19.setName("Registrar Usuario"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boton_registrar_sede, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_mostrar_sedes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campo_buscar_sede, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_buscar_sede, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(boton_regresar_sedes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(boton_modificar_sede, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boton_registrar_sede, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_modificar_sede, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(17, 17, 17)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(campo_buscar_sede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton_buscar_sede)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton_regresar_sedes)
                        .addGap(5, 5, 5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(boton_mostrar_sedes, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_modificar_sedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_modificar_sedeActionPerformed
        // TODO add your handling code here:
        Modificar_Sedes Obj_modificar = new Modificar_Sedes();
        Obj_modificar.setVisible(true);
    }//GEN-LAST:event_boton_modificar_sedeActionPerformed
    /*
    se encarga de llamar a la funcion buscar en la base de datos
    */
    private void boton_buscar_sedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscar_sedeActionPerformed
        // TODO add your handling code here:
        //se obtiene el nombre de la sede que se desea buscar
        String nombre = campo_buscar_sede.getText();
        Mostrar_Sedes buscar = new Mostrar_Sedes();
        
        try {
            //se llama la funcion buscar en la base de datos con el nombre de la sede
            buscar.sacar(nombre);
        } catch (SQLException ex) {
            Logger.getLogger(Offices_window.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        buscar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_buscar_sedeActionPerformed
    /*
    se encarga de acceder a la ventana con la que se realizan registros en la base de datos
    */
    private void boton_registrar_sedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_registrar_sedeActionPerformed
        // TODO add your handling code here:
        Registrar_Sede Obj_registrar = new Registrar_Sede();
        //se hace visible la ventana
        Obj_registrar.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_boton_registrar_sedeActionPerformed
    /*
    se encarga de llamar a la funcion que lista todas las sedes que se han registrado
    */
    private void boton_mostrar_sedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_mostrar_sedesActionPerformed
        // TODO add your handling code here:
        Mostrar_Sedes Obj_mostrar = new Mostrar_Sedes();
        //se obtiene el nombre de la sede que se desea buscar
        String nombre = campo_buscar_sede.getText();
        try {
            Obj_mostrar.imprimir(nombre);
        } catch (SQLException ex) {
            System.out.println("se jodieron");
        }
        Obj_mostrar.setVisible(true);
        
    }//GEN-LAST:event_boton_mostrar_sedesActionPerformed

    private void boton_regresar_sedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_regresar_sedesActionPerformed
        // TODO add your handling code here:
        
        First_window obj_ventana = new First_window();
        obj_ventana.setVisible(true);
        obj_ventana.rol(rol_user);
        this.dispose();
        
    }//GEN-LAST:event_boton_regresar_sedesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_buscar_sede;
    private javax.swing.JButton boton_modificar_sede;
    private javax.swing.JButton boton_mostrar_sedes;
    private javax.swing.JButton boton_registrar_sede;
    private javax.swing.JButton boton_regresar_sedes;
    private javax.swing.JTextField campo_buscar_sede;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
