/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import logica.Consulta_reportes;

/**
 *
 * @author natha9404
 */
public class Reportes_windows extends javax.swing.JFrame {

    /**
     * Creates new form Reportes_windows
     */
    public Reportes_windows() {
        initComponents();
        boton_pqr_ano.setText("<html><p ALIGN=center>PQR</p><p ALIGN=center>realizadas en</p><p ALIGN=center> en cada sede</p><p ALIGN=center> por año</p></html>");
        boton_pqr_mes.setText("<html><p ALIGN=center>PQR</p><p ALIGN=center>realizadas en</p><p ALIGN=center> en cada sede</p><p ALIGN=center> por mes</p></html>");
        boton_envios_mes.setText("<html><p ALIGN=center>Envios realizados</p><p ALIGN=center>en cada sede</p> <p ALIGN=center>por mes</p></html>");
        boton_envios_ano.setText("<html><p ALIGN=center>Envios realizados</p><p ALIGN=center>en cada sede</p> <p ALIGN=center>por año</p></html>");
        boton_envio_usuario_ano.setText("<html><p ALIGN=center>Envios realizados</p><p ALIGN=center>en un año</p> <p ALIGN=center>por cliente</p></html>");
        boton_envio_usuario_mes.setText("<html><p ALIGN=center>Envio realizados</p><p ALIGN=center>en un mes</p> <p ALIGN=center>por cliente</p></html>");
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); 
        setResizable(false);
    }

    String rol_user ="";
    public void rol(String rol) {
        
        //De acuerdo al rol del usuario se habilitan los botones
        //correspondientes a la seguridad.
        rol_user = rol;
        
        
        
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        volver_principal = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        boton_pqr_ano = new javax.swing.JButton();
        boton_envios_mes = new javax.swing.JButton();
        boton_pqr_mes = new javax.swing.JButton();
        boton_envios_ano = new javax.swing.JButton();
        boton_envio_usuario_mes = new javax.swing.JButton();
        boton_envio_usuario_ano = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(157, 215, 255), 3));

        volver_principal.setText("Volver a ventana principal");
        volver_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver_principalActionPerformed(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(153, 204, 255));
        jLabel19.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 204, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/FlashLogo.png"))); // NOI18N
        jLabel19.setText("REPORTES");
        jLabel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel19.setName("Usuarios"); // NOI18N

        boton_pqr_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_pqr_anoActionPerformed(evt);
            }
        });

        boton_envios_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_envios_mesActionPerformed(evt);
            }
        });

        boton_pqr_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_pqr_mesActionPerformed(evt);
            }
        });

        boton_envios_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_envios_anoActionPerformed(evt);
            }
        });

        boton_envio_usuario_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_envio_usuario_mesActionPerformed(evt);
            }
        });

        boton_envio_usuario_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_envio_usuario_anoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(volver_principal))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(boton_pqr_ano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton_envios_ano, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(boton_envio_usuario_ano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_envios_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_pqr_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_envio_usuario_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton_pqr_ano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_pqr_mes, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton_envios_mes, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(boton_envios_ano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton_envio_usuario_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_envio_usuario_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(volver_principal)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volver_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver_principalActionPerformed
        // TODO add your handling code here:
        // se devuelve a la ventana anterior
        First_window obj_ventana_principal = new First_window();
        obj_ventana_principal.setVisible(true);
        obj_ventana_principal.rol(rol_user);
        this.dispose();
    }//GEN-LAST:event_volver_principalActionPerformed

    private void boton_pqr_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_pqr_anoActionPerformed
        // TODO add your handling code here:
        
        Reportes_pqr obj_repor = new Reportes_pqr();
        obj_repor.setVisible(true);
        obj_repor.ano();
        
    }//GEN-LAST:event_boton_pqr_anoActionPerformed

    private void boton_envios_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_envios_mesActionPerformed
        // TODO add your handling code here:
        Reportes_envios obj= new Reportes_envios();
        obj.setVisible(true);
        
    }//GEN-LAST:event_boton_envios_mesActionPerformed

    private void boton_pqr_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_pqr_mesActionPerformed
        // TODO add your handling code here:
        
        Reportes_pqr obj = new Reportes_pqr();
        obj.setVisible(true);
        
        
    }//GEN-LAST:event_boton_pqr_mesActionPerformed

    private void boton_envios_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_envios_anoActionPerformed
        // TODO add your handling code here:
        Reportes_envios obj = new Reportes_envios();
        obj.setVisible(true);
        obj.ano();
    }//GEN-LAST:event_boton_envios_anoActionPerformed

    private void boton_envio_usuario_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_envio_usuario_anoActionPerformed
        // TODO add your handling code here:
        Reportes_envio_user obj= new Reportes_envio_user();
        obj.setVisible(true);
        obj.ano();
        this.dispose();
    }//GEN-LAST:event_boton_envio_usuario_anoActionPerformed

    private void boton_envio_usuario_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_envio_usuario_mesActionPerformed
        // TODO add your handling code here:
        Reportes_envio_user obj= new Reportes_envio_user();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_envio_usuario_mesActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_envio_usuario_ano;
    private javax.swing.JButton boton_envio_usuario_mes;
    private javax.swing.JButton boton_envios_ano;
    private javax.swing.JButton boton_envios_mes;
    private javax.swing.JButton boton_pqr_ano;
    private javax.swing.JButton boton_pqr_mes;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton volver_principal;
    // End of variables declaration//GEN-END:variables
}
